import type {
  Account,
  ApiKey,
  Balance,
  Card,
  ComplianceRecord,
  KycDocument,
  Notification,
  Partner,
  Transaction,
  Transfer,
  User,
  Webhook,
} from "@/lib/types";
import { digestValue } from "@/lib/security";

const now = new Date("2026-03-14T08:00:00.000Z").toISOString();

export const mockPartners: Partner[] = [
  {
    id: "partner-orbit",
    name: "Orbit Treasury",
    slug: "orbit-treasury",
    status: "active",
    tier: "enterprise",
    createdAt: "2025-10-15T10:00:00.000Z",
    settlementAccountId: "acct-orbit-operating",
    settings: {
      allowedWebhookEvents: [
        "account.created",
        "transfer.settled",
        "card.issued",
        "kyc.updated",
      ],
      region: "US",
      riskProfile: "moderate",
    },
  },
  {
    id: "partner-ledgerlane",
    name: "LedgerLane SaaS",
    slug: "ledgerlane-saas",
    status: "onboarding",
    tier: "growth",
    createdAt: "2026-01-08T14:15:00.000Z",
    settlementAccountId: null,
    settings: {
      allowedWebhookEvents: ["account.created", "transfer.settled"],
      region: "US",
      riskProfile: "low",
    },
  },
];

export const mockUsers: User[] = [
  {
    id: "user-platform-admin",
    partnerId: null,
    email: "platform@embeddyfi.dev",
    fullName: "Maya Patel",
    role: "platform_admin",
    status: "active",
    createdAt: "2025-08-01T09:00:00.000Z",
    lastSignInAt: now,
  },
  {
    id: "user-orbit-admin",
    partnerId: "partner-orbit",
    email: "ops@orbit.example",
    fullName: "Ethan Cole",
    role: "partner_admin",
    status: "active",
    createdAt: "2025-10-15T10:05:00.000Z",
    lastSignInAt: now,
  },
  {
    id: "user-orbit-operator",
    partnerId: "partner-orbit",
    email: "finance@orbit.example",
    fullName: "Rina Wu",
    role: "operator",
    status: "active",
    createdAt: "2025-11-01T12:30:00.000Z",
    lastSignInAt: "2026-03-13T16:10:00.000Z",
  },
  {
    id: "user-ledger-admin",
    partnerId: "partner-ledgerlane",
    email: "admin@ledgerlane.example",
    fullName: "Omar Reyes",
    role: "partner_admin",
    status: "invited",
    createdAt: "2026-01-08T14:20:00.000Z",
    lastSignInAt: null,
  },
];

export const mockAccounts: Account[] = [
  {
    id: "acct-orbit-operating",
    partnerId: "partner-orbit",
    userId: "user-orbit-admin",
    accountNumber: "100000013579",
    routingNumber: "011000015",
    type: "operating",
    status: "active",
    nickname: "Primary Operating",
    currency: "USD",
    createdAt: "2025-10-15T10:20:00.000Z",
  },
  {
    id: "acct-orbit-wallet",
    partnerId: "partner-orbit",
    userId: "user-orbit-operator",
    accountNumber: "100000024680",
    routingNumber: "011000015",
    type: "wallet",
    status: "active",
    nickname: "Customer Wallet Sweep",
    currency: "USD",
    createdAt: "2025-11-10T09:15:00.000Z",
  },
  {
    id: "acct-ledger-operating",
    partnerId: "partner-ledgerlane",
    userId: "user-ledger-admin",
    accountNumber: "100000031337",
    routingNumber: "021000021",
    type: "operating",
    status: "pending",
    nickname: "Launch Reserve",
    currency: "USD",
    createdAt: "2026-01-10T09:15:00.000Z",
  },
];

export const mockBalances: Balance[] = [
  {
    id: "bal-orbit-operating",
    partnerId: "partner-orbit",
    accountId: "acct-orbit-operating",
    available: 285400.12,
    pending: 12500,
    ledger: 297900.12,
    currency: "USD",
    updatedAt: now,
  },
  {
    id: "bal-orbit-wallet",
    partnerId: "partner-orbit",
    accountId: "acct-orbit-wallet",
    available: 93210.55,
    pending: 2250,
    ledger: 95460.55,
    currency: "USD",
    updatedAt: now,
  },
  {
    id: "bal-ledger-operating",
    partnerId: "partner-ledgerlane",
    accountId: "acct-ledger-operating",
    available: 0,
    pending: 0,
    ledger: 0,
    currency: "USD",
    updatedAt: now,
  },
];

export const mockTransfers: Transfer[] = [
  {
    id: "tr-1001",
    partnerId: "partner-orbit",
    sourceAccountId: "acct-orbit-operating",
    destinationAccountId: "acct-orbit-wallet",
    amount: 15000,
    currency: "USD",
    rail: "ach",
    status: "settled",
    externalReference: "payroll-sweep-202603",
    initiatedByUserId: "user-orbit-operator",
    createdAt: "2026-03-11T14:30:00.000Z",
    settledAt: "2026-03-12T11:15:00.000Z",
  },
  {
    id: "tr-1002",
    partnerId: "partner-orbit",
    sourceAccountId: "acct-orbit-wallet",
    destinationAccountId: "acct-orbit-operating",
    amount: 4500,
    currency: "USD",
    rail: "book",
    status: "processing",
    externalReference: "reserve-rebalance",
    initiatedByUserId: "user-orbit-admin",
    createdAt: "2026-03-14T04:45:00.000Z",
    settledAt: null,
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn-2001",
    partnerId: "partner-orbit",
    accountId: "acct-orbit-operating",
    transferId: "tr-1001",
    direction: "debit",
    kind: "transfer",
    amount: 15000,
    currency: "USD",
    status: "settled",
    description: "ACH sweep to customer wallet",
    counterparty: "Orbit Treasury",
    metadata: { rail: "ach" },
    createdAt: "2026-03-11T14:30:00.000Z",
    postedAt: "2026-03-12T11:15:00.000Z",
  },
  {
    id: "txn-2002",
    partnerId: "partner-orbit",
    accountId: "acct-orbit-wallet",
    transferId: "tr-1001",
    direction: "credit",
    kind: "deposit",
    amount: 15000,
    currency: "USD",
    status: "settled",
    description: "Wallet funding",
    counterparty: "Orbit Treasury",
    metadata: { rail: "ach" },
    createdAt: "2026-03-11T14:30:00.000Z",
    postedAt: "2026-03-12T11:15:00.000Z",
  },
  {
    id: "txn-2003",
    partnerId: "partner-orbit",
    accountId: "acct-orbit-wallet",
    transferId: "tr-1002",
    direction: "debit",
    kind: "transfer",
    amount: 4500,
    currency: "USD",
    status: "processing",
    description: "Reserve rebalance to operating",
    counterparty: "Orbit Treasury",
    metadata: { rail: "book" },
    createdAt: "2026-03-14T04:45:00.000Z",
    postedAt: "2026-03-14T04:45:00.000Z",
  },
];

export const mockCards: Card[] = [
  {
    id: "card-3001",
    partnerId: "partner-orbit",
    userId: "user-orbit-admin",
    accountId: "acct-orbit-operating",
    cardholderName: "Orbit Treasury Ops",
    brand: "Visa",
    last4: "9481",
    type: "virtual",
    status: "active",
    spendingLimit: 25000,
    createdAt: "2026-02-10T10:00:00.000Z",
    metadata: { purpose: "vendor_disbursements" },
  },
];

export const mockDocuments: KycDocument[] = [
  {
    id: "kyc-4001",
    partnerId: "partner-orbit",
    userId: "user-orbit-admin",
    documentType: "business_registration",
    fileName: "orbit-incorporation.pdf",
    storagePath: null,
    status: "approved",
    notes: "Matched EIN and beneficial owner records.",
    uploadedAt: "2025-10-16T09:00:00.000Z",
    reviewedAt: "2025-10-16T15:30:00.000Z",
    reviewerUserId: "user-platform-admin",
  },
  {
    id: "kyc-4002",
    partnerId: "partner-ledgerlane",
    userId: "user-ledger-admin",
    documentType: "passport",
    fileName: "omar-passport.pdf",
    storagePath: null,
    status: "needs_review",
    notes: "Blurry expiry field.",
    uploadedAt: "2026-01-10T16:30:00.000Z",
    reviewedAt: null,
    reviewerUserId: null,
  },
];

export const mockComplianceRecords: ComplianceRecord[] = [
  {
    id: "comp-5001",
    partnerId: "partner-orbit",
    userId: "user-orbit-admin",
    accountId: "acct-orbit-operating",
    type: "aml",
    status: "monitor",
    riskScore: 48,
    notes: "Elevated payout volume detected over trailing 7 days.",
    createdAt: "2026-03-13T11:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "comp-5002",
    partnerId: "partner-ledgerlane",
    userId: "user-ledger-admin",
    accountId: "acct-ledger-operating",
    type: "kyc",
    status: "restricted",
    riskScore: 76,
    notes: "Beneficial owner identity pending manual review.",
    createdAt: "2026-01-11T09:00:00.000Z",
    updatedAt: now,
  },
];

export const mockApiKeys: ApiKey[] = [
  {
    id: "api-6001",
    partnerId: "partner-orbit",
    name: "Orbit Sandbox SDK",
    prefix: "orbitdemo01",
    keyHash: digestValue("baas.orbitdemo01.secret123"),
    permissions: ["accounts:read", "transfers:write", "webhooks:read"],
    status: "active",
    createdAt: "2026-02-01T13:45:00.000Z",
    lastUsedAt: "2026-03-14T05:00:00.000Z",
  },
];

export const mockWebhooks: Webhook[] = [
  {
    id: "wh-7001",
    partnerId: "partner-orbit",
    url: "https://example-partner.dev/webhooks/banking",
    signingSecret: "whsec_orbit_secret",
    events: ["transfer.settled", "kyc.updated", "card.issued"],
    status: "active",
    createdAt: "2026-02-15T09:45:00.000Z",
    lastDeliveryAt: "2026-03-14T04:46:00.000Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-8001",
    partnerId: "partner-orbit",
    type: "transfer",
    title: "Transfer processing",
    body: "Reserve rebalance tr-1002 is still processing on the ACH rail.",
    severity: "warning",
    createdAt: "2026-03-14T04:46:00.000Z",
    readAt: null,
  },
  {
    id: "notif-8002",
    partnerId: "partner-orbit",
    type: "card",
    title: "Virtual card active",
    body: "Vendor disbursements card is active and ready for use.",
    severity: "info",
    createdAt: "2026-02-10T10:05:00.000Z",
    readAt: "2026-02-10T12:05:00.000Z",
  },
];
